
main: main.cpp square.cpp screen.cpp Rubic.cpp TurnSequence.cpp InStreamable.cpp TurnSequences.cpp Find.cpp AI.cpp
	g++ -Wall -std=c++14 main.cpp square.cpp screen.cpp Rubic.cpp TurnSequence.cpp InStreamable.cpp TurnSequences.cpp Find.cpp AI.cpp -o adventure
